# version: "3.8"

services:
  blog_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blogdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U your_user"]
      interval: 10s
      retries: 5
      timeout: 5s

  blog_api:
    build: .
    command: >
      sh -c "sleep 5 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - blog_db
    ports:
      - "8000:8000"

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    depends_on:
      - blog_api
      - blog_db
      - redis

  redis:
    image: redis:latest

volumes:
  postgres_data: